#include "graph_renderer.h"

#include <cmath>

#include "constants.h"
#include "processing_node.h"

namespace synth_canvas::host {

void GraphRenderer::reserve() {
    _mod_sum_workspace.reserve(constants::kMaxConnectionsPerPort);
    _inputs_workspace.reserve(constants::kMaxConnectionsPerPort);
    _outputs_workspace.reserve(constants::kMaxConnectionsPerPort);
}

void GraphRenderer::render(const GraphProcessor::RenderState& state, AudioBufferManager& buffers,
                           int32_t num_frames, const EventHandler& handler) {
    std::vector<bool> needs_reprocessing(state.sorted_nodes.size(), false);
    bool has_pending_events = false;

    // Phase 1: Standard Audio & Event Processing in topological order
    for (size_t i = 0; i < state.sorted_nodes.size(); ++i) {
        ProcessingNode* node = state.sorted_nodes[i];
        if (!node || !node->isActive()) continue;

        node->setTransport(&(state.transport));
        processSingleNode(i, node, state, buffers, num_frames);
        collectAndRouteEvents(i, node, state, handler, &needs_reprocessing);
    }

    // Phase 2: Intra-block Re-injection Loop for upstream event routing
    int loop_count = 0;
    const int kMaxEventLoops = 64;

    do {
        has_pending_events = false;
        std::vector<bool> current_needs = needs_reprocessing;
        std::fill(needs_reprocessing.begin(), needs_reprocessing.end(), false);

        for (size_t i = 0; i < state.sorted_nodes.size(); ++i) {
            if (!current_needs[i]) continue;
            
            ProcessingNode* node = state.sorted_nodes[i];
            if (!node || !node->isActive()) continue;

            node->processEvents(num_frames);
            
            // Collect events generated by the reprocessing and route them.
            // If they route upstream again, collectAndRouteEvents will set needs_reprocessing[target] = true
            // and we will loop again.
            collectAndRouteEvents(i, node, state, handler, &needs_reprocessing);
        }

        // Check if any new upstream events were generated
        for (bool needs : needs_reprocessing) {
            if (needs) {
                has_pending_events = true;
                break;
            }
        }
        loop_count++;
    } while (has_pending_events && loop_count < kMaxEventLoops);

    if (loop_count >= kMaxEventLoops) {
        // We reached the recursion limit. Events left in queues will naturally
        // be picked up in the next audio block, enforcing a 1-block delay to break the loop safely.
    }
}

void GraphRenderer::renderEvents(const GraphProcessor::RenderState& state, AudioBufferManager& buffers,
                                 int32_t num_frames, const EventHandler& handler) {
    std::vector<bool> needs_reprocessing(state.sorted_nodes.size(), false);
    bool has_pending_events = false;

    // This is essentially just the event portion of render()
    for (size_t i = 0; i < state.sorted_nodes.size(); ++i) {
        ProcessingNode* node = state.sorted_nodes[i];
        if (!node || !node->isActive()) continue;

        node->processEvents(num_frames);
        collectAndRouteEvents(i, node, state, handler, &needs_reprocessing);
    }

    int loop_count = 0;
    const int kMaxEventLoops = 64;

    do {
        has_pending_events = false;
        std::vector<bool> current_needs = needs_reprocessing;
        std::fill(needs_reprocessing.begin(), needs_reprocessing.end(), false);

        for (size_t i = 0; i < state.sorted_nodes.size(); ++i) {
            if (!current_needs[i]) continue;
            
            ProcessingNode* node = state.sorted_nodes[i];
            if (!node || !node->isActive()) continue;

            node->processEvents(num_frames);
            collectAndRouteEvents(i, node, state, handler, &needs_reprocessing);
        }

        for (bool needs : needs_reprocessing) {
            if (needs) {
                has_pending_events = true;
                break;
            }
        }
        loop_count++;
    } while (has_pending_events && loop_count < kMaxEventLoops);
}

void GraphRenderer::processSingleNode(size_t node_index, ProcessingNode* node,
                                      const GraphProcessor::RenderState& state,
                                      AudioBufferManager& buffers, int32_t num_frames) {
    applyParameterModulation(node_index, node, state, num_frames);
    prepareAudioInputs(node_index, node, state, buffers, num_frames);
    prepareAudioOutputs(node, buffers, num_frames);
    executeNodeProcessing(node, num_frames);
}

void GraphRenderer::applyParameterModulation(size_t node_index, ProcessingNode* node,
                                             const GraphProcessor::RenderState& state,
                                             int32_t num_frames) {
    const auto& modulations = state.input_modulations[node_index];
    if (modulations.empty()) return;

    for (int t = 0; t < num_frames; t += constants::kModulationStepSize) {
        _mod_sum_workspace.clear();

        for (const auto& mod : modulations) {
            if (mod.bypass) continue;

            ProcessingNode* src_node = state.sorted_nodes[mod.source_node_index];
            if (!src_node) continue;

            auto* src_buf = src_node->getOutputBuffer(mod.source_port_index);
            if (!src_buf || !src_buf->data32) continue;

            float mod_value = src_buf->data32[0][t] * mod.scale;

            bool found = false;
            for (auto& entry : _mod_sum_workspace) {
                if (entry.first == mod.target_param_id) {
                    entry.second += static_cast<double>(mod_value);
                    found = true;
                    break;
                }
            }

            if (!found) {
                _mod_sum_workspace.emplace_back(mod.target_param_id,
                                                static_cast<double>(mod_value));
            }
        }

        for (const auto& entry : _mod_sum_workspace) {
            double last_offset = node->getParameterModulationOffset(entry.first);
            if (t == 0 || std::abs(entry.second - last_offset) > constants::kModulationThreshold) {
                node->applyModulation(entry.first, entry.second, t);
            }
        }
    }
}

void GraphRenderer::prepareAudioInputs(size_t node_index, ProcessingNode* node,
                                       const GraphProcessor::RenderState& state,
                                       AudioBufferManager& buffers, int32_t num_frames) {
    const auto& input_ports = node->getAudioPorts(true);
    _inputs_workspace.assign(input_ports.size(), clap_audio_buffer{});

    const auto& port_map = state.input_audio_sources[node_index];

    for (size_t i = 0; i < input_ports.size(); ++i) {
        const auto& port_info = input_ports[i];

        AudioBuffer* final_input = nullptr;
        auto it = port_map.find(port_info.index);

        if (it != port_map.end() && !it->second.empty()) {
            const auto& sources = it->second;
            if (sources.size() == 1) {
                const auto& src = sources[0];
                if (!src.bypass) {
                    ProcessingNode* src_node = state.sorted_nodes[src.node_index];
                    if (src_node) final_input = src_node->getOutputBuffer(src.port_index);
                }
            } else {
                AudioBuffer* mix_buf = buffers.getMixBuffer(node_index, port_info.index);
                if (mix_buf) {
                    mix_buf->clear();
                    for (const auto& src : sources) {
                        if (src.bypass) continue;
                        ProcessingNode* src_node = state.sorted_nodes[src.node_index];
                        if (src_node) {
                            AudioBuffer* src_buf = src_node->getOutputBuffer(src.port_index);
                            mix_buf->accumulate(src_buf, num_frames);
                        }
                    }
                    final_input = mix_buf;
                }
            }
        }

        _inputs_workspace[i].channel_count = port_info.clap_info.channel_count;
        _inputs_workspace[i].data32 = final_input ? final_input->data32 : nullptr;
        _inputs_workspace[i].constant_mask = 0;
        _inputs_workspace[i].latency = 0;
        _inputs_workspace[i].data64 = nullptr;
    }
}

void GraphRenderer::prepareAudioOutputs(ProcessingNode* node, AudioBufferManager& buffers,
                                        int32_t num_frames) {
    const auto& output_ports = node->getAudioPorts(false);
    _outputs_workspace.assign(output_ports.size(), clap_audio_buffer{});

    for (size_t i = 0; i < output_ports.size(); ++i) {
        const auto& port_info = output_ports[i];
        AudioBuffer* buf = node->getOutputBuffer(port_info.index);
        if (buf && buf->owns_memory) buf->clear();

        _outputs_workspace[i].channel_count = port_info.clap_info.channel_count;
        _outputs_workspace[i].data32 = buf ? buf->data32 : nullptr;
        _outputs_workspace[i].constant_mask = 0;
        _outputs_workspace[i].latency = 0;
        _outputs_workspace[i].data64 = nullptr;
    }
}

void GraphRenderer::executeNodeProcessing(ProcessingNode* node, int32_t num_frames) {
    node->processBegin(num_frames);
    node->setPorts(static_cast<uint32_t>(_inputs_workspace.size()), _inputs_workspace.data(),
                   static_cast<uint32_t>(_outputs_workspace.size()), _outputs_workspace.data());
    node->process();
    node->processEnd(num_frames);
}

void GraphRenderer::collectAndRouteEvents(size_t node_index, ProcessingNode* node,
                                          const GraphProcessor::RenderState& state,
                                          const EventHandler& handler,
                                          std::vector<bool>* needs_reprocessing) {
    const auto& targets = state.output_event_targets[node_index];
    if (targets.empty()) {
        PluginEvent ev;
        const auto& output_ports = node->getAudioPorts(false);
        for (uint32_t p = 0; p < static_cast<uint32_t>(output_ports.size()); ++p) {
            while (node->popOutputEvent(p, ev)) {
            }
        }
        return;
    }

    const auto& output_ports = node->getAudioPorts(false);
    for (uint32_t p = 0; p < static_cast<uint32_t>(output_ports.size()); ++p) {
        PluginEvent ev;
        while (node->popOutputEvent(p, ev)) {
            for (const auto& target : targets) {
                if (target.bypass || target.source_port_index != p) continue;

                if (target.type == GraphProcessor::RenderState::EventTarget::Type::kNode) {
                    if (ev.event.header.type == CLAP_EVENT_PARAM_MOD &&
                        static_cast<int32_t>(target.target_param_id) != constants::kClapInvalidId) {
                        PluginEvent rewritten_ev = ev;
                        rewritten_ev.event.param_mod.param_id = target.target_param_id;
                        rewritten_ev.event.param_mod.amount *= target.scale;
                        target.destination.node->queueEvent(rewritten_ev);
                    } else {
                        target.destination.node->queueEvent(ev);
                    }
                    
                    // Intra-block re-injection logic:
                    // If we route an event to a node that has ALREADY been processed (or is currently being processed),
                    // flag it so it can process the new event within the same audio block.
                    if (needs_reprocessing) {
                        // Find the index of the destination node
                        auto it = std::find(state.sorted_nodes.begin(), state.sorted_nodes.end(), target.destination.node);
                        if (it != state.sorted_nodes.end()) {
                            size_t dest_index = std::distance(state.sorted_nodes.begin(), it);
                            if (dest_index <= node_index) {
                                (*needs_reprocessing)[dest_index] = true;
                            }
                        }
                    }
                    
                } else if (target.type ==
                           GraphProcessor::RenderState::EventTarget::Type::kExternalOutput) {
                    if (handler) {
                        handler(node, ev, target.destination.port_index);
                    }
                }
            }
        }
    }
}

}  // namespace synth_canvas::host
